package main

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"os"
	"time"
)

type AIProvider interface {
	GenerateContent(ctx context.Context, prompt string) (string, error)
}

type GeminiProvider struct {
	APIKey string
}

func (g *GeminiProvider) GenerateContent(ctx context.Context, prompt string) (string, error) {
	// Using the specific model version you requested
	url := fmt.Sprintf("https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-lite-preview-02-05:generateContent?key=%s", g.APIKey)

	payload := map[string]interface{}{
		"contents": []map[string]interface{}{
			{
				"parts": []map[string]interface{}{
					{"text": prompt},
				},
			},
		},
	}

	jsonData, err := json.Marshal(payload)
	if err != nil {
		return "", err
	}

	req, err := http.NewRequestWithContext(ctx, "POST", url, bytes.NewBuffer(jsonData))
	if err != nil {
		return "", err
	}
	req.Header.Set("Content-Type", "application/json")

	// Explicitly using an http client with a timeout
	client := &http.Client{Timeout: 90 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("gemini api error: %d", resp.StatusCode)
	}

	var result struct {
		Candidates []struct {
			Content struct {
				Parts []struct {
					Text string `json:"text"`
				} `json:"parts"`
			} `json:"content"`
		} `json:"candidates"`
	}

	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return "", err
	}

	if len(result.Candidates) == 0 || len(result.Candidates[0].Content.Parts) == 0 {
		return "", errors.New("no content generated by gemini")
	}

	return result.Candidates[0].Content.Parts[0].Text, nil
}

type DeepSeekProvider struct {
	APIKey string
}

func (d *DeepSeekProvider) GenerateContent(ctx context.Context, prompt string) (string, error) {
	url := "https://api.deepseek.com/v1/chat/completions"

	payload := map[string]interface{}{
		"model": "deepseek-chat",
		"messages": []map[string]interface{}{
			{"role": "user", "content": prompt},
		},
	}

	jsonData, err := json.Marshal(payload)
	if err != nil {
		return "", err
	}

	req, err := http.NewRequestWithContext(ctx, "POST", url, bytes.NewBuffer(jsonData))
	if err != nil {
		return "", err
	}
	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("Authorization", "Bearer "+d.APIKey)

	client := &http.Client{Timeout: 90 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return "", err
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return "", fmt.Errorf("deepseek api error: %d", resp.StatusCode)
	}

	var result struct {
		Choices []struct {
			Message struct {
				Content string `json:"content"`
			} `json:"message"`
		} `json:"choices"`
	}

	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return "", err
	}

	if len(result.Choices) == 0 {
		return "", errors.New("no content generated by deepseek")
	}

	return result.Choices[0].Message.Content, nil
}

type MockProvider struct{}

func (m *MockProvider) GenerateContent(ctx context.Context, prompt string) (string, error) {
	select {
	case <-time.After(500 * time.Millisecond):
	case <-ctx.Done():
		return "", ctx.Err()
	}

	return `# Mock Generation for: ` + prompt + `

## Section 1: Overview
Production keys active. If you see this, check your .env variables.
- Key Point A
- Key Point B

## Section 2: Details
Your session is verified and credits are tracked.
- Image Description: A modern educational interface.

## Conclusion
System operational.`, nil
}

func GetAIProvider() AIProvider {
	// Ensure these environment variable names match what you set in Vercel
	if os.Getenv("MOCK_AI") == "true" {
		return &MockProvider{}
	}
	
	// Check for DeepSeek first if in China or specific env
	if os.Getenv("LOCATION") == "CN" || os.Getenv("DEEPSEEK_KEY") != "" {
		if key := os.Getenv("DEEPSEEK_KEY"); key != "" {
			return &DeepSeekProvider{APIKey: key}
		}
	}

	// Default to Gemini
	if key := os.Getenv("GEMINI_KEY"); key != "" {
		return &GeminiProvider{APIKey: key}
	}

	return &MockProvider{}
}